server:
  port: 8080

spring:
  application:
    name: microservicecloud-consumer
  freemarker: 
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true

